version: "3.9"
services:
  agi-node:
    build: .
    deploy:
      replicas: 3
    ports:
      - "8000-8002:8000"
    networks:
      - agi-mesh-net
    environment:
      - NODE_ID=${HOSTNAME}
      - HEADLESS=true

  weaviate:
    image: semitechnologies/weaviate:1.24.7
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
    ports:
      - "8081:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate

  ui:
    build: .
    command: streamlit run ui.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
    networks:
      - agi-mesh-net

networks:
  agi-mesh-net:
    driver: bridge

volumes:
  weaviate_data:
